# Generated by Django 4.0.3 on 2022-03-17 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='image',
            field=models.ImageField(default='profile.png', upload_to='images'),
        ),
    ]
