# Generated by Django 4.0.3 on 2022-03-28 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_user_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='background_image',
            field=models.ImageField(default='WIN_20220328_15_20_55_Pro.jpg', upload_to='profile_background_image'),
        ),
    ]
