# Generated by Django 4.0.3 on 2022-04-04 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_story'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='account_engaged',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='account_visit',
            field=models.IntegerField(default=0),
        ),
    ]
