# Generated by Django 4.0.3 on 2022-04-04 20:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_user_account_engaged_user_account_visit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='account_engaged',
        ),
        migrations.RemoveField(
            model_name='user',
            name='account_visit',
        ),
        migrations.CreateModel(
            name='UserStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_visit', models.IntegerField(default=0)),
                ('account_engaged', models.IntegerField(default=0)),
                ('user', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
