# Generated by Django 4.0.3 on 2022-04-09 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_remove_user_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='has_viewed',
            field=models.BooleanField(default=False),
        ),
    ]
