# Generated by Django 4.0.3 on 2022-04-17 22:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_user_is_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='post_notification',
            field=models.ManyToManyField(blank=True, related_name='post_notify', to=settings.AUTH_USER_MODEL),
        ),
    ]
