# Generated by Django 4.0.3 on 2022-05-01 11:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_user_display_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='mute_list',
            field=models.ManyToManyField(blank=True, related_name='mute', to=settings.AUTH_USER_MODEL),
        ),
    ]
