# Generated by Django 4.0.3 on 2022-05-01 12:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_user_mute_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='block_list',
            field=models.ManyToManyField(blank=True, related_name='block', to=settings.AUTH_USER_MODEL),
        ),
    ]
