# Generated by Django 4.0.3 on 2022-03-25 21:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0007_alter_notification_blog_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='notify_following',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notify_following', to=settings.AUTH_USER_MODEL),
        ),
    ]
