# Generated by Django 4.0.3 on 2022-03-26 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_notification_notify_following'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
