# Generated by Django 4.0.3 on 2022-03-26 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_mainlike'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MainLike',
        ),
    ]
