# Generated by Django 4.0.3 on 2022-03-29 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0021_blogrepost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogrepost',
            name='text',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.IntegerField(choices=[(1, 'likes'), (2, 'comment'), (3, 'follow'), (4, 'Repost')]),
        ),
    ]
