# Generated by Django 4.0.3 on 2022-04-05 21:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0022_alter_blogrepost_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogrepost',
            name='like',
            field=models.ManyToManyField(blank=True, related_name='repost_like', to=settings.AUTH_USER_MODEL),
        ),
    ]
