# Generated by Django 4.0.3 on 2022-04-08 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0027_alter_notification_notification_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogcomment',
            name='comment',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='repostcomment',
            name='comment',
            field=models.CharField(max_length=500),
        ),
    ]
