# Generated by Django 4.0.3 on 2022-04-18 17:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0036_alter_notification_notification_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='notify_users',
            field=models.ManyToManyField(blank=True, related_name='notify_users', to=settings.AUTH_USER_MODEL),
        ),
    ]
