# Generated by Django 4.0.3 on 2022-04-21 00:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0040_alter_blogrepost_post_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recentsearch',
            name='s',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.recentsearch'),
        ),
    ]
