# Generated by Django 4.0.3 on 2022-04-21 00:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0041_recentsearch_s'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recentsearch',
            name='s',
        ),
    ]
