# Generated by Django 4.0.3 on 2022-04-21 00:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0042_remove_recentsearch_s'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogrepost',
            name='repost',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.blogrepost'),
        ),
    ]
