# Generated by Django 4.0.3 on 2022-04-21 01:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0043_blogrepost_repost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogrepost',
            name='repost',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.blogrepost'),
        ),
    ]
