# Generated by Django 4.0.3 on 2022-04-24 21:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0044_alter_blogrepost_repost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogrepost',
            name='post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.post'),
        ),
    ]
