# Generated by Django 4.0.3 on 2022-04-24 22:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0045_alter_blogrepost_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogimages',
            name='date_posted',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
