# Generated by Django 4.0.4 on 2022-10-13 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0052_alter_post_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='os',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
